### PR TITLE
Updating TEFCA footer

### LINKED ISSUE #2133: Update Footer Component

### PR DESCRIPTION
**Pull request by robertandremitchell**
# PULL REQUEST

## Summary
Updates footer to match new copy here: https://www.figma.com/design/YU5hAHY1Eg7J6gtNbBxm7d/DIBBs-Site-Experiences?node-id=1030-8847&t=hqKzkUvunDwErAfV-0
Also fixes CDC logo to work in both `npm run dev` and `docker compose up`.

## Related Issue
Fixes #2133 

## Additional Information
@bamader , I ran into this issue too: https://skylight-hq.slack.com/archives/C06SXT5PXSQ/p1721075125059879

I took the temporary fix of just modifying the package.json to be limited to shared-resources and ecr-viewer so that the npm install / build would work, but I agree with your take there that it definitely warrants an additional ticket.

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Review by m-goggins — APPROVED** [review]
Looks good to me!

**Review by DanPaseltiner — COMMENTED** [review]
Looks good to me. It's a minor thing, but could we update the CDC logo we are using to match the one in Figma?

**Comment by robertandremitchell** [comment]
> Looks good to me. It's a minor thing, but could we update the CDC logo we are using to match the one in Figma?

@DanPaseltiner , good call, do you know where I can find the updated logo? I'm having trouble just pulling it from figma and the version I found on the CDC website has text: https://onemap.cdc.gov/Portal/home/item.html?id=3ebd072e92834ed3a4e066b90a4e4500&fromSearch=true&searchPosition=1&searchTerm=tags:%22logo%22. 

I found some wikimedia versions, but CDC site also has the logo is copyrighted, so I wanted to avoid any issues there.

**Comment by m-goggins** [comment]
@robertandremitchell Ryan showed me how to export images from Figma yesterday. 

1. In the top right corner, there is a button with `<>` that switches you to dev mode. Click to enable dev mode. 
2. Select the asset you want to export.
3. You can either right click and copy the .png or open the panel on the right, scroll down to export, and select .svg

**Comment by robertandremitchell** [comment]
> @robertandremitchell Ryan showed me how to export images from Figma yesterday.
> 
> 1. In the top right corner, there is a button with `<>` that switches you to dev mode. Click to enable dev mode.
> 2. Select the asset you want to export.
> 3. You can either right click and copy the .png or open the panel on the right, scroll down to export, and select .svg

thanks! I think I gotta ask for edit access because when I click on the `<>` it keeps trying to funnel me into a paid tier. Blah.

**Pull request merged**
