### PR TITLE
Add relevant active problems to eCR Summary section

### LINKED ISSUE #1158: Render associated clinical information in the eCR Summary
## Action Requested
When given an eICR ID and SNOMED condition code in the eCR Viewer, show "clinical results relevant to associated condition" in the eCR summary.

## Acceptance Criteria
The "clinical results relevant to reportable condition" field is filled out for all eCRs where the information is available.

## Testing
We'll likely want unit and integration testing for this feature.

## Designs
[Figma designs](https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=871-2283&mode=design&t=LpQrioiHotZiGBxo-0)

Screenshot 2024-01-25 at 3 45 07 PM

There are three separate types of clinical information that could be displayed here: a diagnosis/problem, a suspected disorder, and a medication. We should consult with Sarah to see if these should all be listed out or separated in some way in the design. 

## Background & Context
When NBS sends a request to the eCR Viewer, it will include two pieces of information: the eICR ID and the SNOMED code for the specific condition a user is viewing. (The condition code is necessary because some eCRs have multiple conditions associated to the RR). Given these two pieces of information, our viewer should be able to render the eCR viewer and the "clinical results relevant to reportable condition".

To do this, we'll need to scan relevant portions of the FHIR bundle for SNOMED codes matching the condition_code parameter. 

## Additional Information
The "associated lab info" ticket (#1157) will probably be tackled first and add the `condition_code` param to the eCR Viewer. This ticket will just be responsible for:
- Finding all clinical results relevant to the condition
- Displaying those results in the eCR Summary

### PR DESCRIPTION
**Pull request by angelathe**
# PULL REQUEST

## Summary
Adds relevant clinical info (active problems) to the eCR Summary section
- Adds `evaluateEcrSummaryRelevantClinicalDetails`: which filters for the relevant active problems given a SNOMED code and returns the relevant clinical details element.
- Adds relevant tests

## Related Issue
Fixes #1158 

## Screenshots
**Given a valid SNOMED code**
Screenshot 2024-06-21 at 09 23 17
**Given an absent or invalid SNOMED code**
Screenshot 2024-06-21 at 09 23 33

## Additional Information
Note: Administered Medications have not been added yet. This task will be scoped to a separate issue since it requires conversion to proper FHIR resources.

## Checklist
Note: No seed data has been stamped yet with condition codes via the trigger-code-reference service. You can test this by:
- [ ] Running the `trigger-code-reference` service on an eICR
    - eICR to try:`61f13d32-b25c-4fb6-998b-73de2dbf87f2`. This particular eCR should stamp 10 resources: 1 Condition and 9 Observations
    - Check `/containers/trigger-code-reference/description.md` for running the service from Python
- [ ] Add the output FHIR bundle to your local db
- [ ] Check the resulting eCR viewer of the bundle, and add `&snomed-code=840539006` (COVID) as a URL search param. This should bubble up relevant COVID active problems to the eCR summary.
    - For `61f13d32-b25c-4fb6-998b-73de2dbf87f2`, it should bubble up the active problem: "Covid Toes".

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by sarahtress** [comment]
@angelathe this is looking great! is it possible to show me what this would look like for 2-3 other eCRs if it's not too much work?

**Comment by sarahtress** [comment]
the only concern I'll note is it seems to me with this one that we're pulling more than what caused the eCR to be sent, but it is still relevant info to COVID... so that might just have to be something we user test (i.e. the only thing that caused this to be sent for COVID is a positive COVID lab test, as defined by the RCKMS Rule Summary, so the COVID toes is just something related to COVID in the record, but not something relevant to why the eCR got sent)

**Comment by angelathe** [comment]
> @angelathe this is looking great! is it possible to show me what this would look like for 2-3 other eCRs if it's not too much work?

@sarahtress I combed through all our seed eCRs, and so far, this is the only eCR that returns a Condition stamped with the COVID condition code. Is there something specific you'd like to see that I can try to re-create with a fake Bundle?

(I'm looking into why some of the eCRs with COVID conditions aren't getting stamped with codes, but that's a separate issue)

**Comment by sarahtress** [comment]
> > @angelathe this is looking great! is it possible to show me what this would look like for 2-3 other eCRs if it's not too much work?
> 
> @sarahtress I combed through all our seed eCRs, and so far, this is the only eCR that returns a Condition stamped with the COVID condition code. Is there something specific you'd like to see that I can try to re-create with a fake Bundle?
> 
> (I'm looking into why some of the eCRs with COVID conditions aren't getting stamped with codes, but that's a separate issue)

ah, if we can only do it for COVID eCRs, then I guess there's not much more for me to look at for now

**Review by BobanL — APPROVED** [review]
Looks great!

**Pull request merged**
