### PR TITLE
Adding Loading Page

### LINKED ISSUE #1760: Create loading skeleton page
## Action Requested
Create a loading skeleton page to improve the loading experience for users.

## Acceptance Criteria
Loading an eCR in the viewer displays the loading skeleton while fetching and then displays the eCR once it's ready.
Associated unit tests are written

## Testing
Does this ticket have unusual testing requirements, or new tests that will need to be created?

## Designs
https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=3076-26718&mode=design&t=pnZDRalBiu9uq67w-0

## Background & Context
Our current loading experience is lackluster and could be greatly improved to give that "something is happening behind the scenes" feel

## Additional Information
A second followup ticket to add a loading "shimmer" effect will be following this ticket.

### PR DESCRIPTION
**Pull request by KennethSkylight**
# PULL REQUEST

## Summary
Adding the ECR Loading Skeleton. How it fits in with the rest of the application will happen when the `loading.js` file can handle loading

## Related Issue
Fixes #1760 

## Checklist
image

### CODE REVIEW

**Comment by sarahtress** [comment]
@KennethSkylight is it possible to download the whole screen and send here? just wanna get a sense of what the full page looks like! what you sent is looking great though!

**Comment by angelathe** [comment]
Code looks good, but @BobanL are the nextJS improvements relevant here? Or can the loading UI stuff only be fixed after your refactoring changes are merged?
@KennethSkylight For reference, [https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming](https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming)

**Comment by BobanL** [comment]
> Code looks good, but @BobanL are the nextJS improvements relevant here? Or can the loading UI stuff only be fixed after your refactoring changes are merged? @KennethSkylight For reference, https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming

Yep these changes currently rely on the improvements I'm making, so right now these will not be visible until my changes get done.

**Comment by angelathe** [comment]
> > Code looks good, but @BobanL are the nextJS improvements relevant here? Or can the loading UI stuff only be fixed after your refactoring changes are merged? @KennethSkylight For reference, https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming
> 
> Yep these changes currently rely on the improvements I'm making, so right now these will not be visible until my changes get done.

Ok thanks! @KennethSkylight could you write a ticket to follow up later on making the loading UI files match the new NextJS structure after @BobanL gets his PR in?

**Review by angelathe — APPROVED** [review]

**Pull request merged**
