### PR TITLE
Add SNOMED code for Diagnosis Interpretation to Problem template

### LINKED ISSUE #2350: Condition resources are not always created during FHIR conversion
## Description

In several eCRs, active problems are not being converted to FHIR. In the examples below, the UUID's are being generated but the `Condition` Resources themselves are not being created.

This is also important because when eCRs are triggered by specific conditions, the Relevant Conditions section might show "No matching clinical data found" if the Active Problems data isn’t available due to incorrect FHIR conversion.

## Steps to reproduce

For each eCR example, you can confirm bug exists by comparing the (lack of) active problems clinical info in the eCR Viewer to the HTML view of the eICR.

#### Example eCRs:
- `6100896d-b520-497c-b2fe-1c111c679274`: [Link](http://localhost:3000/view-data?id=6100896d-b520-497c-b2fe-1c111c679274)
- `cf9e1db8-fcc5-4cbc-96cd-043d3fd65bac`: [Link](http://localhost:3000/view-data?id=cf9e1db8-fcc5-4cbc-96cd-043d3fd65bac)
- `df33f075-83a1-4d28-ba63-05bcc3339c21`: [Link](http://localhost:3000/view-data?id=df33f075-83a1-4d28-ba63-05bcc3339c21)
- Also found in a TDH sample eCR we received (#8, LYME)

## Expected Result

The number of Condition FHIR resources created, along with their content, should accurately reflect what is in the original eCR.

## Actual result

In the example below (`df33f075-83a1-4d28-ba63-05bcc3339c21`), you should see that while active problems are listed in the HTML view, no active problems should appear in the eCR Viewer.

#### Priority
- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

- This will require FHIR conversion work.
- Related files:
    - `containers/fhir-converter/Templates/eCR/Resource/_Condition.liquid`
    - `containers/fhir-converter/Templates/eCR/Entry/Problem/_entry_act_entryRelationship.liquid`

**Potential Problem**: We have this conditional statement to create Condition resources:
```
{% if probRelationship.observation.code.code == "64572001" or probRelationship.observation.code.code == "55607006" or probRelationship.observation.code.translation.code == "64572001" or probRelationship.observation.code.translation.code == "55607006" -%}
```
But all the eCRs mentioned above have an` observation.code.code = 282291009` that isn't included in this statement. `282291009` has the concept name "Diagnosis interpretation (observable entity)." 

**Potential solution** I think that including `282291009` in the conditional statement will fix this issue

### PR DESCRIPTION
**Pull request by austin-hall-skylight**
# PULL REQUEST

## Summary
Problems with SNOMED code 282291009 (diagnosis interpretation) will now be mapped to condition resources in the FHIR bundle.

## Related Issue
Fixes #2350

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by BobanL** [comment]
> Anyone know why the lighthouse test is failing? The eCR mentioned in the logs shouldn't have been affected by this ticket

It seems like that is failing on accessibility. The condition summary section is h3 and then the lab accordion is h5 which breaks that rule
image
This change seems like it did add additional data to that section
image

**Comment by BobanL** [comment]
> @BobanL @austin-hall-skylight Just checked, and I think our ticket didn't directly cause the change -- `data.sql` wasn’t updated before with previous changes merged to main.
> 
> Since the fix will be changing the heading level for `AccordionLabResults`, thoughts on:
> 
> 1. creating new ticket that changes heading level & updates `data.sql` & snapshot tests?
> 2. updating `data.sql` merging this PR to main

That sounds good to me!

**Comment by angelathe** [comment]
@BobanL ready for re-review, thanks!!

**Review by BobanL — APPROVED** [review]
😄

**Pull request merged**
