### PR TITLE
Fix TEFCA Customize Query Nav Tab Styling

### LINKED ISSUE #2372: Fix nav tab styling

### PR DESCRIPTION
**Pull request by robertandremitchell**
# PULL REQUEST

## Summary
This _should_ fix the styling of the navigation tab (Labs/Medication/Conditions) to more closely align with the Figma: https://www.figma.com/design/YU5hAHY1Eg7J6gtNbBxm7d/DIBBs-Site-Experiences?m=dev

The primary fixes:
* left-aligning the tabs
* updating the :after effect to have a blue underline in addition to bolding
* aligning the hr align beneath nav tab with the new underline.
* fixed the padding around `include all` to match figma.

## Related Issue
Fixes #2372 

## Additional Information
I carried over many of the stylings from figma, however, the `font-family: "Source Sans Pro";` looks...wrong? The default font looks more like the picture, but we can add that back if we want to align?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by lg-king** [comment]
The margin between the nav items should be 32 (right now it's 16). Otherwise I think the nav tab looks good. The spacing is also a little off between the "query" heading but I think that's an issue with the "query" text padding (should be 32 between query name/nav bar, and 4 between query name and "customize query"). The font looks ok to me, it may just look off because the page background is different in figma?

**Comment by robertandremitchell** [comment]
> The margin between the nav items should be 32 (right now it's 16). Otherwise I think the nav tab looks good. The spacing is also a little off between the "query" heading but I think that's an issue with the "query" text padding (should be 32 between query name/nav bar, and 4 between query name and "customize query"). The font looks ok to me, it may just look off because the page background is different in figma?

thanks, Laura! I think I fixed up the gap on nav items and the text padding. let me know what you think

**Comment by lg-king** [comment]
It looks like there's now too much space - I think the issue is that there is both a margin and padding, making the total space between 48 now (looks like 16px after the text and then another 32 between the items): 
Screen Shot 2024-08-14 at 9 49 21 AM

**Comment by robertandremitchell** [comment]
> It looks like there's now too much space - I think the issue is that there is both a margin and padding, making the total space between 48 now (looks like 16px after the text and then another 32 between the items): Screen Shot 2024-08-14 at 9 49 21 AM

ahhh, good check. should be fixed now!

**Review by lg-king — APPROVED** [review]
looks good!

**Review by bamader — APPROVED** [review]
LGTM! Thanks for getting the tab nav stylings in, this looks way better.

**Pull request merged**
