### PR TITLE
TEFCA Viewer: MRN Search

### LINKED ISSUE #1841: Implement MRN search

### PR DESCRIPTION
**Pull request by DanPaseltiner**
# PULL REQUEST

## Summary
To prep for the demo we will be doing at CSTE we needed to make a couple minor updates.

1. Enable searching on MRN as this is what we would like to demo.
2. Correct race and ethnicity rendering
3. Add order date for medication requests

fixes #1841

### CODE REVIEW

**Review by robertmitchellv — APPROVED** [review]
still getting my bearings with the TEFCA viewer but these changes look good to me 🚀

**Comment by robertandremitchell** [comment]
code looks good, but @DanPaseltiner , is there a MRN we can test with? Or a place to look for test data?

**Comment by DanPaseltiner** [comment]
> code looks good, but @DanPaseltiner , is there a MRN we can test with? Or a place to look for test data?

@robertandremitchell you can give `34972316` a shot. This is the MRN for Veronica Blackstone, a synthetic patient on the MELD server that has data for chlamydia, syphilis, and social determinants of health.

**Review by robertandremitchell — APPROVED** [review]

**Review by bamader — APPROVED** [review]
LGTM. Forgot how much I hated looking at JS 🤣

**Pull request merged**
