### PR TITLE
Add eICR Custodian Details

### LINKED ISSUE #2517: Add "eICR Custodian Details" section to eCR Metadata
## User Story

As an eCR coordinator, I want to be able to see the custodian information for the eCR encounter. This will help me troubleshoot the eCR.

## Acceptance Criteria

- [ ] `eICR Custodian Details` section added to `eCR Metadata Info` section
- [ ] eICR Custodian Details section includes:
    - [ ] Custodian ID
    - [ ] Custodian Name
    - [ ] Custodian Address
    - [ ] Custodian Contact
- [ ] If these fields are not present in the eCR document, they are added to the `Unavailable Info` section
- [ ] The data in the fields should match the data found in the xml in the `custodian > assignedCustodian` section of the xml

## Scenarios

**Scenario 1:** 
- When viewing an eCR, I want to know the custodian of the eCR data
- When I scroll down to the `eCR Metadata Info` section, I can see `Custodian Details` section in the Viewer
- The fields are listed in the order below:
  - Custodian ID
  - Custodian Name
  - Custodian Address
  - Custodian Contact
- The data that I can see in this section corresponds exactly to the data I see in the `custodian > assignedCustodian` section of the xml
- When I scroll down to Unavailable Info section, I see any fields we didn't have data for in the correct order

## Design Notes

[Link to Figma design in Dev mode](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer-(Aug-Dec-2024)?node-id=7006-93&node-type=CANVAS&m=dev)

_Screenshots below should not be used for working on this ticket - always refer to Figma design for most up-to-date designs:_

## Additional context

There's a good deal of similar, author-related information within an eCR - facility, provider, author, custodian, etc. We haven't been displaying Custodian information, but we need to.

This spreadsheet has more information about where in the eCR spec Provider information can be found: [eCR Viewer Field Mapping](https://cdc.sharepoint.com/:x:/r/teams/OPHDST-IRD-DIBBs/Shared%20Documents/CDC%20DIBBs%20Project/Streamline%20Team/1%20-%20Pilot%20eCR%20Viewer%202024/5%20-%20Research%20%26%20Design/Design/eCR%20Viewer%20Field%20Mapping.xlsx?d=w80a53c04215840b6a7762dfc8b7267c9&csf=1&web=1&e=RIiBPb)

area to look at in spreadsheet highlighted in red box:

### PR DESCRIPTION
**Pull request by angelathe**
# PULL REQUEST

## Summary
Main story:
- Add eICR Custodian Details to the eCR Metadata section
- Update snapshot and unit tests
- Update loading page

## Related Issue
Fixes #2517 

## Acceptance Criteria
- [ ] `eICR Custodian Details` section added to `eCR Metadata Info` section
- [ ] eICR Custodian Details section includes:
    - [ ] Custodian ID
    - [ ] Custodian Name
    - [ ] Custodian Address
    - [ ] Custodian Contact
- [ ] If these fields are not present in the eCR document, they are added to the `Unavailable Info` section
- [ ] The data in the fields should match the data found in the xml in the `custodian > assignedCustodian` section of the xml

## Additional Information
**Example eCR**: http://localhost:3000/ecr-viewer/view-data?id=1.2.840.114350.1.13.297.3.7.8.688883.567479#eicr-custodian-details
**Custodian details** (from XML):
```
    <custodian>
        <assignedCustodian>
            <representedCustodianOrganization>
                <id extension="51" root="1.2.840.114350.1.13.297.3.7.2.696570" />
                <name>Hoag Memorial Hospital</name>
                <telecom use="WP" value="tel:+1-949-764-8400" />
                <addr use="WP">
                    <streetAddressLine>1 HOAG DR</streetAddressLine>
                    <county>ORANGE</county>
                    <city>NEWPORT BEACH</city>
                    <state>CA</state>
                    <postalCode>92663-4162</postalCode>
                    <country>USA</country>
                </addr>
            </representedCustodianOrganization>
        </assignedCustodian>
    </custodian>
```
**Screenshot**:
Screenshot 2024-09-25 at 13 37 33

## Checklist
- [ ] Check for several eCRs that the data in the `eICR Custodian Details` sub-section matches the the data you see in the `custodian > assignedCustodian` section of the xml

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by sarahtress** [comment]
@angelathe this looks good to me, except for one thing - when I click on `eICR Custodian Details` in the side nav, it doesn't actually bring me down to that section and seems to be the only one doing that. not sure what's going wrong there but I  had to manually scroll to that section to view it

**Comment by angelathe** [comment]
> @angelathe this looks good to me, except for one thing - when I click on `eICR Custodian Details` in the side nav, it doesn't actually bring me down to that section and seems to be the only one doing that. not sure what's going wrong there but I had to manually scroll to that section to view it

@sarahtress Oops sorry about that! I think I fixed it if you want to check it again

**Comment by sarahtress** [comment]
> > @angelathe this looks good to me, except for one thing - when I click on `eICR Custodian Details` in the side nav, it doesn't actually bring me down to that section and seems to be the only one doing that. not sure what's going wrong there but I had to manually scroll to that section to view it
> 
> @sarahtress Oops sorry about that! I think I fixed it if you want to check it again

that's okay I believe you! lol

**Review by lina-roth — APPROVED** [review]
LGTM!

**Pull request merged**
