### PR TITLE
PatientID tooltip

### PR DESCRIPTION
**Pull request by aviars**
# PULL REQUEST

## Summary
What changes are being proposed?
Adding a patient ID tooltip.

## Related Issue
Fixes part of #
[Add tooltips to eCR Viewer Fields [1/2]](https://app.zenhub.com/workspaces/streamline-ecr-6480bf2ee530095ab41ebbe9/issues/gh/cdcgov/phdi/1477)

## Additional Information
Anything else the review team should know?

If this looks good, I'll backfill the rest.

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by aviars** [comment]
Screenshot 2024-04-23 at 11 50 05 AM

**Comment by KennethSkylight** [comment]
@sarahtress should the tooltip be on the value or on the title?

**Comment by sarahtress** [comment]
> @sarahtress should the tooltip be on the value or on the title?

it should be on the field name (which I think you're calling the title here?). for ex: if there was a tooltip on DOB, you'd see the tooltip when hovering over "DOB", not when hovering over "4/23/24"

**Comment by aviars** [comment]
Closing in favor of #1703

**Pull request closed without merging**
