### PR TITLE
Austin/2481 encounter reason diagnosis

### LINKED ISSUE #2481: Add "Encounter Diagnosis" and "Encounter Reason" to Encounter section
## User Story

As a user, I want to see more info about encounters, so that I can better understand the case report I'm viewing.

## Acceptance Criteria

- [ ] Add "Encounter Diagnosis" to encounter details
- [ ] Add "Encounter Reason" to encounter details
- [ ] Missing fields are included in the unavailable info section
- [ ] Update tests

## Scenarios

- I open an eCR in the viewer
- I now see more detailed information about the encounter

## Design Notes

[Link to Figma design in Dev mode](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer-(Aug-Dec-2024)?node-id=7006-93&node-type=CANVAS&m=dev)

_Screenshots below should not be used for working on this ticket - always refer to Figma design for most up-to-date designs:_

### PR DESCRIPTION
**Pull request by austin-hall-skylight**
# PULL REQUEST

## Summary
Add encounter diagnosis and encounter reason to ecr summary and encounter details

## Related Issue
Fixes #2481 

## Acceptance Criteria
 - [ ] Add "Encounter Diagnosis" to encounter details
 - [ ]  Add "Encounter Reason" to encounter details
 - [ ]  Missing fields are included in the unavailable info section
 - [ ]  Update tests

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by JNygaard-Skylight** [comment]
Could you add or update an integration test for the FHIR converter to test the liquid changes?

**Comment by austin-hall-skylight** [comment]
> Could you add or update an integration test for the FHIR converter to test the liquid changes?

Will do, thanks for the suggestion.

**Comment by austin-hall-skylight** [comment]
Going to remove encounter reason for now. I got some feedback from Sarah that she wants to use ["Reason for the initiation" (2.16.840.1.113883.10.20.15.2.3.5)](https://github.com/HL7/CDA-phcaserpt-1.3.0/blob/ca898f29d68ff073e129808489868131710eca85/examples/samples/CDAR2_IG_PHCASERPT_R2_D3_SAMPLE_MANUAL.xml#L402) which is being added in 3.1.

**Comment by austin-hall-skylight** [comment]
> Going to remove encounter reason for now. I got some feedback from Sarah that she wants to use ["Reason for the initiation" (2.16.840.1.113883.10.20.15.2.3.5)](https://github.com/HL7/CDA-phcaserpt-1.3.0/blob/ca898f29d68ff073e129808489868131710eca85/examples/samples/CDAR2_IG_PHCASERPT_R2_D3_SAMPLE_MANUAL.xml#L402) which is being added in 3.1.

It's ready for review again.

**Review by BobanL — APPROVED** [review]
👍

**Pull request merged**
