### PR TITLE
added record linkage envs

### PR DESCRIPTION
**Pull request by nickbristow**
# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #

## Additional Information
Anything else the review team should know?

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Review by DanPaseltiner — COMMENTED** [review]
Where do the values of these secrets actually get stored?

**Comment by nickbristow** [comment]
> Where do the values of these secrets actually get stored?

in the key vault

**Review by emmastephenson — APPROVED** [review]
LGTM, thanks Nick!

**Review by DanPaseltiner — APPROVED** [review]
Thanks Nick!

**Pull request closed without merging**
