### PR TITLE
Correct h2 and h3 Sizes

### LINKED ISSUE #2170: Increase font size of "eCR Document" header | eCR Viewer
## Action Requested
In the eCR Viewer, the `eCR Document` header is really small. It should be the same font size as `eCR Summary`.

**Current font size**: 22px
**Should be**: 40px

**Currently:**

## Acceptance Criteria
eCR Document header should be changed to 40px

**Important! Please change this for both:**
- [ ] The main eCR Viewer page
- [ ] The loading page component

## Testing
Snapshot tests may need to be updated.

## Designs
[Figma designs](https://www.figma.com/design/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?node-id=1606-27619&t=BDaWATonROGgZ3So-0)

## Background & Context
`eCR Summary` header uses the code below from `custom-styles.scss`
```
#ecr-summary {
  font-size: 40px;
}
```

## Additional Information
**Related files:**
- `src/styles/custom-styles.scss`
- **Main page**: `src/app/view-data/page.tsx`
- **Loading page**: `src/app/view-data/components/LoadingComponent.tsx`

### PR DESCRIPTION
**Pull request by JNygaard-Skylight**
# PULL REQUEST

## Summary
Corrected the size of "eCR Document". It should now use the same styling as the other `<h2>` "eCR Summary". In addition, fixed the headers within the eCR Summary to correctly be `<h3>`s instead of `<h2>`s.

## Related Issue
Fixes #2170 

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by JNygaard-Skylight** [comment]
@sarahtress this is ready for review. Can you also have a look at the eCR Summary headers ("Patient Summary", "Encounter Summary", and "Condition Summary")? I had to change their CSS to fix the "eCR Document".
image
image

**Comment by sarahtress** [comment]
@JNygaard-Skylight just seeing some alignment/padding issues. I'm going to mark up where I see issues on the screenshots, and then hopefully you can investigate the designs in dev mode to get all of the exact measurements? let me know

352573534-f9ba0301-d1a8-4615-b840-2386c0e39cb6

352573333-d22dbab4-ac38-4901-8e5d-7b05225960e7

**Comment by JNygaard-Skylight** [comment]
@sarahtress I fixed the margins and double checked the font sizes:
image

**Comment by sarahtress** [comment]
looks good to me!

**Review by BobanL — APPROVED** [review]

**Pull request merged**
