### PR TITLE
Retrieve RCKMS ValueSet -> CodeSet mappings for Trigger Code Reference API

### PR DESCRIPTION
**Pull request by ericbuckley**
# PULL REQUEST

## Summary
A new script that can parse data from an RCKMS docx archive file, then query the NIH UMLS API to retrieve information about the ValueSets extracted.  The bulk of the retrieval work should be complete in this PR, the remaining step will be to add this data to the SQlite database so the TCR API can query it for results.

## Related Issue
Fixes #

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Review by robertandremitchell — COMMENTED** [review]
Overall looks good! I was having some trouble locally with this test.


```bash
(.venv) rob@Roberts-MacBook-Pro trigger-code-reference % pytest -vv -s seed-scripts/test_seed_rckms_database.py::TestQueryValueSetAPI::test_query_valueset_api_retries

==================================================================== test session starts ====================================================================
platform darwin -- Python 3.10.14, pytest-8.2.0, pluggy-1.5.0 -- /Users/rob/phdi/containers/trigger-code-reference/.venv/bin/python3.10
cachedir: .pytest_cache
rootdir: /Users/rob/phdi
configfile: pytest.ini
plugins: anyio-4.3.0
collected 1 item                                                                                                                                            

seed-scripts/test_seed_rckms_database.py::TestQueryValueSetAPI::test_query_valueset_api_retries FAILED

========================================================================= FAILURES ==========================================================================
___________________________________________________ TestQueryValueSetAPI.test_query_valueset_api_retries ____________________________________________________

    def query_valueset_api(oid: str, retries: int = 2) -> dict:
        """
        Query the NIH UMLS RetrieveValueSet API with the given OID.
    
        :param oid: The OID to query.
        :param retries: The number of retries to attempt if the request fails.
    
        :return: The response from the API.
        """
        # encode the API key as a base64 string
        b64auth = base64.b64encode(f"apikey:{UMLS_API_KEY}".encode()).decode()
        # create a urllib request with the path and parameters
        req = urllib.request.Request(f"https://cts.nlm.nih.gov/fhir/ValueSet/{oid}/$expand")
        # add the authorization header to the request
        req.add_header("Authorization", f"Basic {b64auth}")
        req.add_header("Accept", "application/fhir+json; fhirVersion=4.0.1")
        try:
            # open the request and read the response
>           with urllib.request.urlopen(req) as f:

seed-scripts/seed_rckms_database.py:240: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1114: in __call__
    return self._mock_call(*args, **kwargs)
/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1118: in _mock_call
    return self._execute_mock_call(*args, **kwargs)
/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1173: in _execute_mock_call
    raise effect
seed-scripts/seed_rckms_database.py:240: in query_valueset_api
    with urllib.request.urlopen(req) as f:
/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1114: in __call__
    return self._mock_call(*args, **kwargs)
/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1118: in _mock_call
    return self._execute_mock_call(*args, **kwargs)
/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1173: in _execute_mock_call
    raise effect
seed-scripts/seed_rckms_database.py:240: in query_valueset_api
    with urllib.request.urlopen(req) as f:
/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1114: in __call__
    return self._mock_call(*args, **kwargs)
/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1118: in _mock_call
    return self._execute_mock_call(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <MagicMock name='urlopen' id='4410126640'>, args = (<urllib.request.Request object at 0x106e147c0>,), kwargs = {}, effect = <HTTPError 500: 'Error'>

    def _execute_mock_call(self, /, *args, **kwargs):
        # separate from _increment_mock_call so that awaited functions are
        # executed separately from their call, also AsyncMock overrides this method
    
        effect = self.side_effect
        if effect is not None:
            if _is_exception(effect):
>               raise effect
E               urllib.error.HTTPError: HTTP Error 500: Error

/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1173: HTTPError

During handling of the above exception, another exception occurred:

self = <test_seed_rckms_database.TestQueryValueSetAPI testMethod=test_query_valueset_api_retries>, mock_urlopen = <MagicMock name='urlopen' id='4410126640'>

    @unittest.mock.patch("seed_rckms_database.UMLS_API_KEY", new="key")
    @unittest.mock.patch("urllib.request.urlopen")
    def test_query_valueset_api_retries(self, mock_urlopen):
        """Test the query_valueset_api function retries."""
        mock_response = unittest.mock.MagicMock()
        mock_response.read.return_value = b'{"key": "value"}'
        mock_response.__enter__.return_value = mock_response  # For the with statement
        mock_urlopen.return_value = mock_response
        # Have the mock function raise an exception the first time it is called
        # and then return a valid response the second time it is called
        mock_urlopen.side_effect = [
            urllib.error.HTTPError("http://example.com", 500, "Error", {}, None),
            mock_response,
        ]
        result = srd.query_valueset_api("1", retries=1)
        assert result == {"key": "value"}
        # Have the mock function always raise an exception
        mock_urlopen.side_effect = urllib.error.HTTPError(
            "http://example.com", 500, "Error", {}, None
        )
        with self.assertRaises(urllib.error.HTTPError):
>           srd.query_valueset_api("1", retries=2)

seed-scripts/test_seed_rckms_database.py:274: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
seed-scripts/seed_rckms_database.py:249: in query_valueset_api
    return query_valueset_api(oid, retries - 1)
seed-scripts/seed_rckms_database.py:249: in query_valueset_api
    return query_valueset_api(oid, retries - 1)
seed-scripts/seed_rckms_database.py:255: in query_valueset_api
    e.add_note(msg)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def __getattr__(self, name):
        # Attribute lookups are delegated to the underlying file
        # and cached for non-numeric results
        # (i.e. methods are cached, closed and friends are not)
        file = self.__dict__['file']
>       a = getattr(file, name)
E       AttributeError: '_io.BytesIO' object has no attribute 'add_note'

/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tempfile.py:494: AttributeError
================================================================== short test summary info ==================================================================
FAILED seed-scripts/test_seed_rckms_database.py::TestQueryValueSetAPI::test_query_valueset_api_retries - AttributeError: '_io.BytesIO' object has no attribute 'add_note'
===================================================================== 1 failed in 0.22s =====================================================================
(.venv) rob@Roberts-MacBook-Pro trigger-code-reference % 

```


Good level of documentation, I think the only other bit of documentation that would be helpful is how to obtain an NIH UMLS API key.

**Comment by ericbuckley** [comment]
> Overall looks good! I was having some trouble locally with this test. I tried a few edits, but couldn't get this one going, unfortunately.
> 
> ```shell
> (.venv) rob@Roberts-MacBook-Pro trigger-code-reference % pytest -vv -s seed-scripts/test_seed_rckms_database.py::TestQueryValueSetAPI::test_query_valueset_api_retries
> 
> ==================================================================== test session starts ====================================================================
> platform darwin -- Python 3.10.14, pytest-8.2.0, pluggy-1.5.0 -- /Users/rob/phdi/containers/trigger-code-reference/.venv/bin/python3.10
> cachedir: .pytest_cache
> rootdir: /Users/rob/phdi
> configfile: pytest.ini
> plugins: anyio-4.3.0
> collected 1 item                                                                                                                                            
> 
> seed-scripts/test_seed_rckms_database.py::TestQueryValueSetAPI::test_query_valueset_api_retries FAILED
> 
> ========================================================================= FAILURES ==========================================================================
> ___________________________________________________ TestQueryValueSetAPI.test_query_valueset_api_retries ____________________________________________________
> 
>     def query_valueset_api(oid: str, retries: int = 2) -> dict:
>         """
>         Query the NIH UMLS RetrieveValueSet API with the given OID.
>     
>         :param oid: The OID to query.
>         :param retries: The number of retries to attempt if the request fails.
>     
>         :return: The response from the API.
>         """
>         # encode the API key as a base64 string
>         b64auth = base64.b64encode(f"apikey:{UMLS_API_KEY}".encode()).decode()
>         # create a urllib request with the path and parameters
>         req = urllib.request.Request(f"https://cts.nlm.nih.gov/fhir/ValueSet/{oid}/$expand")
>         # add the authorization header to the request
>         req.add_header("Authorization", f"Basic {b64auth}")
>         req.add_header("Accept", "application/fhir+json; fhirVersion=4.0.1")
>         try:
>             # open the request and read the response
> >           with urllib.request.urlopen(req) as f:
> 
> seed-scripts/seed_rckms_database.py:240: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1114: in __call__
>     return self._mock_call(*args, **kwargs)
> /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1118: in _mock_call
>     return self._execute_mock_call(*args, **kwargs)
> /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1173: in _execute_mock_call
>     raise effect
> seed-scripts/seed_rckms_database.py:240: in query_valueset_api
>     with urllib.request.urlopen(req) as f:
> /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1114: in __call__
>     return self._mock_call(*args, **kwargs)
> /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1118: in _mock_call
>     return self._execute_mock_call(*args, **kwargs)
> /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1173: in _execute_mock_call
>     raise effect
> seed-scripts/seed_rckms_database.py:240: in query_valueset_api
>     with urllib.request.urlopen(req) as f:
> /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1114: in __call__
>     return self._mock_call(*args, **kwargs)
> /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1118: in _mock_call
>     return self._execute_mock_call(*args, **kwargs)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
> self = <MagicMock name='urlopen' id='4410126640'>, args = (<urllib.request.Request object at 0x106e147c0>,), kwargs = {}, effect = <HTTPError 500: 'Error'>
> 
>     def _execute_mock_call(self, /, *args, **kwargs):
>         # separate from _increment_mock_call so that awaited functions are
>         # executed separately from their call, also AsyncMock overrides this method
>     
>         effect = self.side_effect
>         if effect is not None:
>             if _is_exception(effect):
> >               raise effect
> E               urllib.error.HTTPError: HTTP Error 500: Error
> 
> /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1173: HTTPError
> 
> During handling of the above exception, another exception occurred:
> 
> self = <test_seed_rckms_database.TestQueryValueSetAPI testMethod=test_query_valueset_api_retries>, mock_urlopen = <MagicMock name='urlopen' id='4410126640'>
> 
>     @unittest.mock.patch("seed_rckms_database.UMLS_API_KEY", new="key")
>     @unittest.mock.patch("urllib.request.urlopen")
>     def test_query_valueset_api_retries(self, mock_urlopen):
>         """Test the query_valueset_api function retries."""
>         mock_response = unittest.mock.MagicMock()
>         mock_response.read.return_value = b'{"key": "value"}'
>         mock_response.__enter__.return_value = mock_response  # For the with statement
>         mock_urlopen.return_value = mock_response
>         # Have the mock function raise an exception the first time it is called
>         # and then return a valid response the second time it is called
>         mock_urlopen.side_effect = [
>             urllib.error.HTTPError("http://example.com", 500, "Error", {}, None),
>             mock_response,
>         ]
>         result = srd.query_valueset_api("1", retries=1)
>         assert result == {"key": "value"}
>         # Have the mock function always raise an exception
>         mock_urlopen.side_effect = urllib.error.HTTPError(
>             "http://example.com", 500, "Error", {}, None
>         )
>         with self.assertRaises(urllib.error.HTTPError):
> >           srd.query_valueset_api("1", retries=2)
> 
> seed-scripts/test_seed_rckms_database.py:274: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> seed-scripts/seed_rckms_database.py:249: in query_valueset_api
>     return query_valueset_api(oid, retries - 1)
> seed-scripts/seed_rckms_database.py:249: in query_valueset_api
>     return query_valueset_api(oid, retries - 1)
> seed-scripts/seed_rckms_database.py:255: in query_valueset_api
>     e.add_note(msg)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> 
>     def __getattr__(self, name):
>         # Attribute lookups are delegated to the underlying file
>         # and cached for non-numeric results
>         # (i.e. methods are cached, closed and friends are not)
>         file = self.__dict__['file']
> >       a = getattr(file, name)
> E       AttributeError: '_io.BytesIO' object has no attribute 'add_note'
> 
> /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tempfile.py:494: AttributeError
> ================================================================== short test summary info ==================================================================
> FAILED seed-scripts/test_seed_rckms_database.py::TestQueryValueSetAPI::test_query_valueset_api_retries - AttributeError: '_io.BytesIO' object has no attribute 'add_note'
> ===================================================================== 1 failed in 0.22s =====================================================================
> (.venv) rob@Roberts-MacBook-Pro trigger-code-reference % 
> ```
> 
> Good level of documentation, I think the only other bit of documentation that would be helpful is how to obtain an NIH UMLS API key.

@robertandremitchell thanks for taking a look and I'll add some more documentation for obtaining a UMLS key.  As for the error, I believe its because the `exception.add_note` function was added in Python 3.11, but you ran the tests in python 3.10.  I can remove that feature, but before I do so, what version of Python does this service support?  I was assuming 3.11 based on this file https://github.com/CDCgov/phdi/blob/main/containers/dibbs/Dockerfile#L1

**Comment by robertandremitchell** [comment]
> > Overall looks good! I was having some trouble locally with this test. I tried a few edits, but couldn't get this one going, unfortunately.
> > ```shell
> > (.venv) rob@Roberts-MacBook-Pro trigger-code-reference % pytest -vv -s seed-scripts/test_seed_rckms_database.py::TestQueryValueSetAPI::test_query_valueset_api_retries
> > 
> > ==================================================================== test session starts ====================================================================
> > platform darwin -- Python 3.10.14, pytest-8.2.0, pluggy-1.5.0 -- /Users/rob/phdi/containers/trigger-code-reference/.venv/bin/python3.10
> > cachedir: .pytest_cache
> > rootdir: /Users/rob/phdi
> > configfile: pytest.ini
> > plugins: anyio-4.3.0
> > collected 1 item                                                                                                                                            
> > 
> > seed-scripts/test_seed_rckms_database.py::TestQueryValueSetAPI::test_query_valueset_api_retries FAILED
> > 
> > ========================================================================= FAILURES ==========================================================================
> > ___________________________________________________ TestQueryValueSetAPI.test_query_valueset_api_retries ____________________________________________________
> > 
> >     def query_valueset_api(oid: str, retries: int = 2) -> dict:
> >         """
> >         Query the NIH UMLS RetrieveValueSet API with the given OID.
> >     
> >         :param oid: The OID to query.
> >         :param retries: The number of retries to attempt if the request fails.
> >     
> >         :return: The response from the API.
> >         """
> >         # encode the API key as a base64 string
> >         b64auth = base64.b64encode(f"apikey:{UMLS_API_KEY}".encode()).decode()
> >         # create a urllib request with the path and parameters
> >         req = urllib.request.Request(f"https://cts.nlm.nih.gov/fhir/ValueSet/{oid}/$expand")
> >         # add the authorization header to the request
> >         req.add_header("Authorization", f"Basic {b64auth}")
> >         req.add_header("Accept", "application/fhir+json; fhirVersion=4.0.1")
> >         try:
> >             # open the request and read the response
> > >           with urllib.request.urlopen(req) as f:
> > 
> > seed-scripts/seed_rckms_database.py:240: 
> > _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> > /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1114: in __call__
> >     return self._mock_call(*args, **kwargs)
> > /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1118: in _mock_call
> >     return self._execute_mock_call(*args, **kwargs)
> > /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1173: in _execute_mock_call
> >     raise effect
> > seed-scripts/seed_rckms_database.py:240: in query_valueset_api
> >     with urllib.request.urlopen(req) as f:
> > /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1114: in __call__
> >     return self._mock_call(*args, **kwargs)
> > /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1118: in _mock_call
> >     return self._execute_mock_call(*args, **kwargs)
> > /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1173: in _execute_mock_call
> >     raise effect
> > seed-scripts/seed_rckms_database.py:240: in query_valueset_api
> >     with urllib.request.urlopen(req) as f:
> > /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1114: in __call__
> >     return self._mock_call(*args, **kwargs)
> > /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1118: in _mock_call
> >     return self._execute_mock_call(*args, **kwargs)
> > _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> > 
> > self = <MagicMock name='urlopen' id='4410126640'>, args = (<urllib.request.Request object at 0x106e147c0>,), kwargs = {}, effect = <HTTPError 500: 'Error'>
> > 
> >     def _execute_mock_call(self, /, *args, **kwargs):
> >         # separate from _increment_mock_call so that awaited functions are
> >         # executed separately from their call, also AsyncMock overrides this method
> >     
> >         effect = self.side_effect
> >         if effect is not None:
> >             if _is_exception(effect):
> > >               raise effect
> > E               urllib.error.HTTPError: HTTP Error 500: Error
> > 
> > /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/mock.py:1173: HTTPError
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > self = <test_seed_rckms_database.TestQueryValueSetAPI testMethod=test_query_valueset_api_retries>, mock_urlopen = <MagicMock name='urlopen' id='4410126640'>
> > 
> >     @unittest.mock.patch("seed_rckms_database.UMLS_API_KEY", new="key")
> >     @unittest.mock.patch("urllib.request.urlopen")
> >     def test_query_valueset_api_retries(self, mock_urlopen):
> >         """Test the query_valueset_api function retries."""
> >         mock_response = unittest.mock.MagicMock()
> >         mock_response.read.return_value = b'{"key": "value"}'
> >         mock_response.__enter__.return_value = mock_response  # For the with statement
> >         mock_urlopen.return_value = mock_response
> >         # Have the mock function raise an exception the first time it is called
> >         # and then return a valid response the second time it is called
> >         mock_urlopen.side_effect = [
> >             urllib.error.HTTPError("http://example.com", 500, "Error", {}, None),
> >             mock_response,
> >         ]
> >         result = srd.query_valueset_api("1", retries=1)
> >         assert result == {"key": "value"}
> >         # Have the mock function always raise an exception
> >         mock_urlopen.side_effect = urllib.error.HTTPError(
> >             "http://example.com", 500, "Error", {}, None
> >         )
> >         with self.assertRaises(urllib.error.HTTPError):
> > >           srd.query_valueset_api("1", retries=2)
> > 
> > seed-scripts/test_seed_rckms_database.py:274: 
> > _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> > seed-scripts/seed_rckms_database.py:249: in query_valueset_api
> >     return query_valueset_api(oid, retries - 1)
> > seed-scripts/seed_rckms_database.py:249: in query_valueset_api
> >     return query_valueset_api(oid, retries - 1)
> > seed-scripts/seed_rckms_database.py:255: in query_valueset_api
> >     e.add_note(msg)
> > _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
> > 
> >     def __getattr__(self, name):
> >         # Attribute lookups are delegated to the underlying file
> >         # and cached for non-numeric results
> >         # (i.e. methods are cached, closed and friends are not)
> >         file = self.__dict__['file']
> > >       a = getattr(file, name)
> > E       AttributeError: '_io.BytesIO' object has no attribute 'add_note'
> > 
> > /opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tempfile.py:494: AttributeError
> > ================================================================== short test summary info ==================================================================
> > FAILED seed-scripts/test_seed_rckms_database.py::TestQueryValueSetAPI::test_query_valueset_api_retries - AttributeError: '_io.BytesIO' object has no attribute 'add_note'
> > ===================================================================== 1 failed in 0.22s =====================================================================
> > (.venv) rob@Roberts-MacBook-Pro trigger-code-reference % 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Good level of documentation, I think the only other bit of documentation that would be helpful is how to obtain an NIH UMLS API key.
> 
> @robertandremitchell thanks for taking a look and I'll add some more documentation for obtaining a UMLS key. As for the error, I believe its because the `exception.add_note` function was added in Python 3.11, but you ran the tests in python 3.10. I can remove that feature, but before I do so, what version of Python does this service support? I was assuming 3.11 based on this file https://github.com/CDCgov/phdi/blob/main/containers/dibbs/Dockerfile#L1

ah yeah that makes sense. We semi-recently moved from 3.10 to 3.11, so this is right. Thanks for catching and tests worked with that change.

**Comment by robertandremitchell** [comment]
@ericbuckley , I wanted to confirm before approving that this PR was in fact ready for review? Currently it is still marked as a draft. are there other todo's/updates that should be made in this PR?

**Comment by ericbuckley** [comment]
@robertandremitchell sorry about that, I meant to open it up.  There is still some database work left, so the RCKMS integration is a work in progress, but I thought this would be a good place to merge.

**Review by robertandremitchell — APPROVED** [review]

**Pull request merged**
