### PR TITLE
[RELEASE] v1.1.0

### PR DESCRIPTION
**Pull request by m-goggins**
# PULL REQUEST

## Summary
Adds new MPI schema, data access layer, and updates record linkage

## Related Issue
Fixes #

## Additional Information
Anything else the review team should know?

## Checklist

- [x] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Review by BradySkylight — APPROVED** [review]
I almost wonder if this is a 'major' change though?  maybe we go to 1.1.0?

**Comment by m-goggins** [comment]
@BradySkylight that's a good point. It is definitely a breaking change.

**Comment by m-goggins** [comment]
@DanielPaseltiner @emmastephenson thoughts on making this a major change per Brady's suggestion. I just bumped to 1.1.0

**Comment by emmastephenson** [comment]
> @DanielPaseltiner @emmastephenson thoughts on making this a major change per Brady's suggestion. I just bumped to 1.1.0

@m-goggins if it's a breaking change, I'm definitely on board with making this a major version release.

**Review by emmastephenson — APPROVED** [review]
LGTM!

**Comment by DanPaseltiner** [comment]
We have definitely changed the API of functions within the SDK although not the APIs of any containerized services. Until we actually get around to refactoring the code base have a more limited reliance on the SDK (and possibly stop publishing to PyPi) I think we should bump the minor version. I'm in favor of moving to `1.1.0`.

**Pull request merged**
