### PR TITLE
Emergency Contact

### LINKED ISSUE #1120: Add Patient Emergency Contact to eCR Viewer
## Action Requested
Add a field for Patient Emergency Contact to the eCR Viewer.
> eCR Viewer
>> Patient Info
>>> Demographics
>>>> Emergency Contact

## Acceptance Criteria
Patient emergency contact is displayed for all eCRs where the information is available.

## Testing
Unit testing will be required.

## Designs
[Figma link](https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=871-2283&mode=design&t=sxIe5Umchzr49IHv-0)

## Background & Context
This field may not be covered by our FHIR Converter, so we may need to update that before adding to the eCR Viewer.

### PR DESCRIPTION
**Pull request by JNygaard-Skylight**
# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #1120 

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by JNygaard-Skylight** [comment]
@sarahtress Here's what the emergency contact looks like in the ECR Viewer
image

**Comment by sarahtress** [comment]
@JNygaard-Skylight looks good to me thanks!

**Comment by angelathe** [comment]
> @sarahtress Here's what the emergency contact looks like in the ECR Viewer image

When I pulled down the branch, I tried running the eCR viewer for this userID but Emergency Contact information didn't show up like it does in the screenshot above (showed as N/A in the unavailable info section) -- @JNygaard-Skylight Do you know what I might be doing wrong?

**Comment by JNygaard-Skylight** [comment]
> > @sarahtress Here's what the emergency contact looks like in the ECR Viewer image
> 
> When I pulled down the branch, I tried running the eCR viewer for this userID but Emergency Contact information didn't show up like it does in the screenshot above (showed as N/A in the unavailable info section) -- @JNygaard-Skylight Do you know what I might be doing wrong?
 
For that particular screenshot, I had manually edited the ECR to have an emergency contact with an address and phone number.

**Review by angelathe — APPROVED** [review]
LGTM! At somepoint, it might be nice to add seed data that has emergency contact info that we could see in the ecr viewer

**Pull request merged**
