### PR TITLE
Add service specific openapi schema

### PR DESCRIPTION
**Pull request by bamader**
# PULL REQUEST

## Summary
This PR relocates the auto-generated FastAPI schema for the message-refiner to a service-specific location so that terraform can properly hit it.

## Related Issue
Fix 3 of 3 (on PHDI) for redoc issues

### CODE REVIEW

**Comment by bamader** [comment]
@robertandremitchell That's weird, I updated the branch, pulled everything down with fresh images (no cache), and am seeing successful builds. I've also verified that openapi.json is properly served at `message-refiner/openapi.json` and that we can locally load both the `/redoc` and `/docs` pages with the new service prepending. Maybe it's a caching thing for you? Or the image wasn't actually "published" yet?

**Comment by bamader** [comment]
The test I added to check the redoc location is also passing now which would seem to indicate that everything is in order, too

**Review by robertandremitchell — COMMENTED** [review]
weird, yeah, I had to pip reinstall `dibbs` but that seemed to do the trick for the pytest, but not for actually starting up the service. Still poking at it.


```bash
(.venv) rob@Roberts-MacBook-Pro message-refiner % docker compose up --build
[+] Building 0.5s (22/22) FINISHED                   docker:desktop-linux
 => [trigger-code-reference-service internal] load build definition  0.0s
 => => transferring dockerfile: 364B                                 0.0s
 => [message-refiner-service internal] load metadata for ghcr.io/cd  0.0s
 => [trigger-code-reference-service internal] load .dockerignore     0.0s
 => => transferring context: 2B                                      0.0s
 => [message-refiner-service 1/7] FROM ghcr.io/cdcgov/phdi/dibbs:la  0.0s
 => [trigger-code-reference-service internal] load build context     0.1s
 => => transferring context: 15.88MB                                 0.1s
 => CACHED [message-refiner-service 2/7] WORKDIR /code               0.0s
 => CACHED [trigger-code-reference-service 3/8] COPY ./requirements  0.0s
 => CACHED [trigger-code-reference-service 4/8] RUN pip install -r   0.0s
 => CACHED [trigger-code-reference-service 5/8] COPY ./app /code/ap  0.0s
 => CACHED [trigger-code-reference-service 6/8] COPY ./assets /code  0.0s
 => CACHED [trigger-code-reference-service 7/8] COPY ./seed-scripts  0.0s
 => CACHED [trigger-code-reference-service 8/8] COPY ./description.  0.0s
 => [trigger-code-reference-service] exporting to image              0.0s
 => => exporting layers                                              0.0s
 => => writing image sha256:279b0d476fc010233d57f483752b012c7d8fe1d  0.0s
 => => naming to docker.io/library/message-refiner-trigger-code-ref  0.0s
 => [message-refiner-service internal] load build definition from D  0.0s
 => => transferring dockerfile: 325B                                 0.0s
 => [message-refiner-service internal] load .dockerignore            0.0s
 => => transferring context: 2B                                      0.0s
 => [message-refiner-service internal] load build context            0.0s
 => => transferring context: 1.01MB                                  0.0s
 => CACHED [message-refiner-service 3/7] COPY ./requirements.txt /c  0.0s
 => CACHED [message-refiner-service 4/7] RUN pip install -r require  0.0s
 => CACHED [message-refiner-service 5/7] COPY ./app /code/app        0.0s
 => CACHED [message-refiner-service 6/7] COPY ./assets /code/assets  0.0s
 => CACHED [message-refiner-service 7/7] COPY ./description.md /cod  0.0s
 => [message-refiner-service] exporting to image                     0.0s
 => => exporting layers                                              0.0s
 => => writing image sha256:f79c41f40c057d57dd20112fec65ad96dcf44b2  0.0s
 => => naming to docker.io/library/message-refiner-message-refiner-  0.0s
[+] Running 2/0
 ✔ Container message-refiner-trigger-code-reference-service-1  Running0.0s 
 ✔ Container message-refiner-message-refiner-service-1         Created0.0s 
Attaching to message-refiner-service-1, trigger-code-reference-service-1
message-refiner-service-1         | Traceback (most recent call last):
message-refiner-service-1         |   File "/usr/local/bin/uvicorn", line 8, in <module>
message-refiner-service-1         |     sys.exit(main())
message-refiner-service-1         |              ^^^^^^
message-refiner-service-1         |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
message-refiner-service-1         |     return self.main(*args, **kwargs)
message-refiner-service-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
message-refiner-service-1         |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
message-refiner-service-1         |     rv = self.invoke(ctx)
message-refiner-service-1         |          ^^^^^^^^^^^^^^^^
message-refiner-service-1         |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
message-refiner-service-1         |     return ctx.invoke(self.callback, **ctx.params)
message-refiner-service-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
message-refiner-service-1         |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
message-refiner-service-1         |     return __callback(*args, **kwargs)
message-refiner-service-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
message-refiner-service-1         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 410, in main
message-refiner-service-1         |     run(
message-refiner-service-1         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 577, in run
message-refiner-service-1         |     server.run()
message-refiner-service-1         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
message-refiner-service-1         |     return asyncio.run(self.serve(sockets=sockets))
message-refiner-service-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
message-refiner-service-1         |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
message-refiner-service-1         |     return runner.run(main)
message-refiner-service-1         |            ^^^^^^^^^^^^^^^^
message-refiner-service-1         |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
message-refiner-service-1         |     return self._loop.run_until_complete(task)
message-refiner-service-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
message-refiner-service-1         |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
message-refiner-service-1         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
message-refiner-service-1         |     await self._serve(sockets)
message-refiner-service-1         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
message-refiner-service-1         |     config.load()
message-refiner-service-1         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 434, in load
message-refiner-service-1         |     self.loaded_app = import_from_string(self.app)
message-refiner-service-1         |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
message-refiner-service-1         |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
message-refiner-service-1         |     module = importlib.import_module(module_str)
message-refiner-service-1         |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
message-refiner-service-1         |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
message-refiner-service-1         |     return _bootstrap._gcd_import(name[level:], package, level)
message-refiner-service-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
message-refiner-service-1         |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
message-refiner-service-1         |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
message-refiner-service-1         |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
message-refiner-service-1         |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
message-refiner-service-1         |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
message-refiner-service-1         |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
message-refiner-service-1         |   File "/code/app/main.py", line 24, in <module>
message-refiner-service-1         |     app = BaseService(
message-refiner-service-1         |           ^^^^^^^^^^^^
message-refiner-service-1         | TypeError: BaseService.__init__() got an unexpected keyword argument 'openapi_url'
message-refiner-service-1 exited with code 1


```

**Review by robertandremitchell — APPROVED** [review]
> Ugh. Have you tried nuking all of the stuff and rebuilding everything fresh?

advanced nuking did the trick! looks good on both

`http://localhost:8080/message-refiner/redoc`
`http://localhost:8080/redoc`

**Pull request merged**
