### PR TITLE
County Name

### LINKED ISSUE #1119: Add Patient County to eCR Viewer
## Action Requested
Add a field for Patient County to the eCR Viewer.
> eCR Viewer
>> Patient Info
>>> Demographics
>>>> County

## Acceptance Criteria
Patient county is displayed for all eCRs that have a patient address field.

## Testing
Unit testing will be required.

## Designs
[Figma link](https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=871-2283&mode=design&t=sxIe5Umchzr49IHv-0)

## Background & Context
This field should be returned when available from our geocoding service, but we need to make sure it's being added into the FHIR bundle appropriately.

### PR DESCRIPTION
**Pull request by JNygaard-Skylight**
# PULL REQUEST

## Summary
What changes are being proposed?

## Related Issue
Fixes #1119

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by JNygaard-Skylight** [comment]
When there is no county information: 
image

**Comment by emmastephenson** [comment]
@joshnygaard can you assign reviewers for this PR? TIA! Guessing it should be Sarah + Nick, and maybe Marcelle too? She's familiar with the geocoding service.

**Comment by sarahtress** [comment]
> When there is no county information: image

@JNygaard-Skylight  do you have any examples of when County is available?

**Comment by JNygaard-Skylight** [comment]
@sarahtress, here's when we have a county.
image

**Comment by sarahtress** [comment]
> @sarahtress, here's when we have a county. image

@JNygaard-Skylight awesome, looks great!

**Review by emmastephenson — APPROVED** [review]
Looks great, thanks Josh!

**Pull request merged**
