### PR TITLE
use SNOMED to determine condition and rule summary

### LINKED ISSUE #2100: BUG: Reportable Condition and RCKMS Rule Summary displays 1st instead of relevant condition
## Action Requested
Reportable Condition and RCKMS Rule Summary currently displays the **first** condition/rule, rather than the **relevant** condition/rule.

AS a user, I want to view the correct relevant condition in the eCR summary 
SO THAT I can view the reportable condition alongside the clinical info and lab results relevant to that condition.

## Acceptance Criteria

GIVEN that a valid SNOMED code has been included as a search parameter
WHEN a user views the eCR Summary (About the Condition sub-section)
THEN the Relevant Condition and RCKMS Rule Summary should display the correct associated condition

## Testing

Unit tests will likely need to be added.

## Designs

Designs can be found in [Figma](https://www.figma.com/design/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?node-id=3160-36760&t=s5dhkyoYtOyxvMIL-0). Please consult with Sarah about what text should be displayed when no condition is specified as a URL param.

## Background & Context

**Currently**, we are only pulling the **first** condition/RCKS rule summary to the eCR summary, even when there are multiple relevant conditions. Instead, we should be pulling the relevant condition/RCKS rule that is specified in our search params.

- Ex: If we include `&snomed-code=840539006` (COVID) in the search params, then the relevant condition shown should be COVID-related text (and not any of the other relevant condition(s)). **Changing the snomed code search params should alter what relevant condition is shown in the eCR Summary.**

## Additional Information

**Relevant Files:**
- `evaluateEcrSummaryAboutTheConditionDetails` function in `src/app/services/ecrSummaryService.ts`
- Tests should likely be added in `ecrSummaryService.test.ts`
- `seed-ecr-viewer-config.json` - config file for eCR viewer that (manually) lists which conditions should be stamped by the trigger code reference service

### Local dev testing:
1. Run `npm run convert-seed-data` to stamp bundles
    1. Check whether or not conditions have already been added to be stamped in `orchestration/app/custom_configs/seed-ecr-viewer-config.json`, otherwise, may need to manually add snomed codes for testing. (At the time of writing this ticket, only COVID -- 840539006 -- is being stamped).
2. Kill docker and run `npm run local-dev`

Then, add snomed code to search param: [http://localhost:3000/view-data?id=testid&snomed-code=1234](http://localhost:3000/view-data?id=1.2.840.114350.1.13.478.3.7.8.688883.230886#ecr-metadata)

Check that relevant condition/RCKMS rule is being displayed in the eCR summary, and changing the SNOMED search param should also change the relevant condition.

### PR DESCRIPTION
**Pull request by BobanL**
# PULL REQUEST

## Summary
- Use SNOMED to determine which condition and summary should be displayed

## Related Issue
Fixes #2100 

## Demo
[SNOMED provided](http://localhost:3000/view-data?id=1.2.840.114350.1.13.478.3.7.8.688883.230886&snomed-code=840539006)
image

[No SNOMED provided](http://localhost:3000/view-data?id=1.2.840.114350.1.13.478.3.7.8.688883.230886) 
image

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by sarahtress** [comment]
@BobanL could you add 8px of paragraph spacing for these fields? right now they're too bunch together and it's hard to tell where new lines start without the paragraph spacing. thanks!

**Comment by BobanL** [comment]
@sarahtress New screenshots with padding!
image
image

**Comment by sarahtress** [comment]
awesome, looks good to me!

**Review by angelathe — APPROVED** [review]
🎉

**Pull request merged**
