### PR TITLE
Adding Procedures to eCR Viewer

### LINKED ISSUE #1108: Add Procedures to eCR Viewer
## Action Requested
Add the "Procedures" field to the eCR Viewer.
>eCR Viewer
>> Clinical Info
>>> Treatment Details
>>>> Procedures

## Acceptance Criteria
Procedures are displayed for eCRs that have the field.

## Testing
Unit testing will be required.

## Background & Context
This field may be a list of sub-fields.

## Designs
[Figma link](https://www.figma.com/file/tXWUeV3Kjehd7VNqHojZYq/eCR-Viewer?type=design&node-id=1024-136062&mode=design&t=sxIe5Umchzr49IHv-0)

## Additional Information
We'll need to test to see whether or not this field is already being converted to FHIR, or if we'll need to complete both FHIR conversion and adding to the eCR Viewer.

Procedures may be a list, so if it seems difficult to incorporate all available information into the design, please chat with Sarah.

### PR DESCRIPTION
**Pull request by KennethSkylight**
# PULL REQUEST

## Summary
Procedures is not currently being pulled by FHIR converter so the liquid files have been modified to pull them in. To add the procedures, it is built on top of the ClinicalInfo component. 

There also isn't any current designs for the procedures so this is just how I guessed to do it.

## Related Issue
Fixes #1108 

## Screenshots
image

### CODE REVIEW

**Comment by KennethSkylight** [comment]
@sarahtress it is indeed a real one I found in the LAC data haha

**Comment by KennethSkylight** [comment]
@sarahtress Added the line

image

**Comment by sarahtress** [comment]
> @sarahtress Added the line
> 
> image

looks great! thanks

**Review by BobanL — APPROVED** [review]
👍

**Pull request merged**
