### PR TITLE
Remove redundant Python Linting

### PR DESCRIPTION
**Pull request by JNygaard-Skylight**
# PULL REQUEST

## Summary
Remove Python linting and formatting as a step in the pipeline. This already happens in `pre-commit` and that also gets ran as part of the pipeline.

## Related Issue
Fixes #

## Additional Information
Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Review by DanPaseltiner — CHANGES_REQUESTED** [review]
Since it is possible to push changes without running pre-commit this would effectively allow for bypassing linting which I don't think is what we want. What is the problem we are trying to solve here?

**Comment by JNygaard-Skylight** [comment]
> Since it is possible to push changes without running pre-commit this would effectively allow for bypassing linting which I don't think is what we want. What is the problem we are trying to solve here?

Sure you can skip pre-commit when you push changes, but doesn't pre-commit get ran as a a pipeline action, and isn't it required?

No problems, just thought I could remove a few lines of code.

**Comment by DanPaseltiner** [comment]
> > Since it is possible to push changes without running pre-commit this would effectively allow for bypassing linting which I don't think is what we want. What is the problem we are trying to solve here?
> 
> Sure you can skip pre-commit when you push changes, but doesn't pre-commit get ran as a a pipeline action, and isn't it required?
> 
> No problems, just thought I could remove a few lines of code.

I completely forgot that the pre-commit runs automatically when changes are merged into a PR. Trying to confirm that pre-commit passing is required to merge. Basically I just want to ensure that the code has to pass linting before being allowed to merge.

**Comment by DanPaseltiner** [comment]
So it doesn't appear to me that a successful run of pre-commit is required for merging. Am I missing something in the configs for settings for the repo? I guess the case I'm concerned about is when `ruff` fails and can't correct the issue.

**Pull request closed without merging**
