### PR TITLE
ecr library search by name

### LINKED ISSUE #2602: SEARCH - Searching by Name + Search Bar
## User Story

As a case investigator, I want to search by a patient's name, so that I can find all their relevant eCRs in the Library.

## Acceptance Criteria

- [x] The search bar is rendered according to the designs
    - [x] Default text is included when search bar is not in use
- [x] Searching by any part of a patient's name pulls up all matching eCRs

NOT an acceptance criteria: we're just doing strict search at this point, not fuzzy matching. If I search "Jon", I'm not going to see any patients named "John" (note different spelling).

## Scenarios

Scenario 1:
- I click on the search bar at the top of the Library
- I type "Emma" and click the button for search
- All eCRs for any "Emma"s are listed (i.e., "Emma Alpha" "Emmaline Bravo" "Gemma Charlie" or "Jane Emma" are all shown)

Scenario 2: 
- I click on the search bar at the top of the Libary
- I type "John" and hit the enter button 
- All eCRs for any "John"s are listed (i.e., "John Doe", "Johnny Smith" "Jane Johnson")

## Design Notes

[Link to Figma design in Dev mode](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer-(Aug-Dec-2024)?node-id=4955-47258&m=dev)
_No search prototype available_

_Screenshots below should not be used for working on this ticket - always refer to Figma design for most up-to-date designs:_

### PR DESCRIPTION
**Pull request by BobanL**
# PULL REQUEST

## Summary
What changes are being proposed?
- Add search bar for eCR Viewer
- Remove duplicate DB

## Related Issue
Fixes #2602

## Acceptance Criteria
- [ ] The search bar is rendered according to the designs
    - [ ] Default text is included when search bar is not in use
- [ ] Searching by any part of a patient's name pulls up all matching eCRs

NOT an acceptance criteria: we're just doing strict search at this point, not fuzzy matching. If I search "Jon", I'm not going to see any patients named "John" (note different spelling).

## Additional Information
image
image
https://github.com/user-attachments/assets/d958364f-06fc-40dd-947c-8a274052efc1

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by BobanL** [comment]
Ready for design review @ashton-skylight!

**Comment by ashton-skylight** [comment]
Looks great! Thanks @bobanl

**Comment by gordonfarrell** [comment]
The one funky thing with it right now is that there's no way to get back from your search to the full list without refreshing the page. Is that going to be covered by the clear filters button that I think is coming in another ticket?

**Review by gordonfarrell — APPROVED** [review]
Asked Emma about the search clearing, that'll be covered in another ticket. Looks good thanks Boban, love all the tests!

**Pull request merged**
