### PR TITLE
Add Scheduled Orders to Plan of Treatment 

### LINKED ISSUE #1105: Add Scheduled Orders to eCR Viewer
## Action Requested
Add the "Pending Results" field to the eCR Viewer.
>eCR Viewer
>> Clinical Info
>>> Treatment Details
>>>> Plan of Treatment
>>>>> Scheduled Orders

## Acceptance Criteria
Scheduled Orders are displayed for eCRs that have the field.

## Testing
Unit testing will be required.

## Background & Context
This is likely a list with multiple labs included.

## Additional Information
We'll need to test to see whether or not this field is already being converted to FHIR, or if we'll need to complete both FHIR conversion and adding to the eCR Viewer.

Scheduled orders are slightly different from pending results - pending results are for labs a patient has undergone but that are awaiting results, while scheduled orders are labs that a patient must take but hasn't yet done.

### PR DESCRIPTION
**Pull request by lina-roth**
# PULL REQUEST

Screen Shot 2024-04-17 at 11 21 08 AM

## Summary
- Adding function for returning scheduled orders table

## Related Issue
Fixes #1105 

## Additional Information
Anything else the review team should know?

- Only 1 ECR had Scheduled Orders - 1.2.840.114350.1.13.297.3.7.8.688883.567479

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by nickbristow** [comment]
For some reason when i download the branch and go to  1.2.840.114350.1.13.297.3.7.8.688883.567479, I see plan of treatment as unavailable?

**Comment by lina-roth** [comment]
> For some reason when i download the branch and go to 1.2.840.114350.1.13.297.3.7.8.688883.567479, I see plan of treatment as unavailable?

hmmm weird. its working for me

**Comment by sarahtress** [comment]
@lina-roth this looks good to me! thanks

**Review by BobanL — APPROVED** [review]
I was able to see the data!  Changes look good to me!

image

**Pull request merged**
