### PR TITLE
Update TEFCA Header

### LINKED ISSUE #2129: Update Header Component

### PR DESCRIPTION
**Pull request by robertandremitchell**
# PULL REQUEST

## Summary
Updates header to align with figma: https://www.figma.com/design/YU5hAHY1Eg7J6gtNbBxm7d/DIBBs-Site-Experiences?node-id=2252-27322&t=UAEaLDV6mECgEZwb-0

## Related Issue
Fixes #2129 

## Additional Information
* Should the logo also be clickable to go back to home page like the TEFCA Viewer page text?
* The sizing of the logo and TEFCA Viewer text seems...odd. I copied the dimensions from figma and it seems fine in docker, maybe a tad smaller in npm run dev. It still seems a little smaller than it should be, including the text, but when I bump text to the next biggest font size, it looks too big? Idk, maybe my eyeballs are not working well.
* More of an FYI, once those questions about the logo are answered, we will comment out that section of code because the DIBBs logo is not approved yet. But figured it was better to get those questions answered first so that once approval is obtained, it's just a matter of uncommenting the code.

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Review by bamader — COMMENTED** [review]
Agree with both of Marcelle's points (particularly the font size bump up--I hate small text in web apps 😅 ). I say we bump it up to `xl` and implement that redirect and then we'll be good to go.

**Comment by robertandremitchell** [comment]
> This looks good to me! To answer your questions:
> 
> * I think clicking on `TEFCA Viewer` (or the DIBBs logo whenever it is approved) should take you to the home page.
> * I agree the text for TEFCA Viewer looks a little small, but it could be because the DIBBs logo is so large?  I messed around with the logo dimensions but ultimately bumped up the size to font-sans-xl and thought it looked good.
> 
> image

thanks! makes sense, updates should be present now.

**Comment by m-goggins** [comment]
I think this has come up before and is only a problem running locally (but I can't remember), but when I click on the logo it brings me back to `http://localhost:3000/tefca-viewer` which does not exist. I wanted to confirm that when it's deploy, it will return to the actual home page.

**Comment by robertandremitchell** [comment]
> I think this has come up before and is only a problem running locally (but I can't remember), but when I click on the logo it brings me back to `http://localhost:3000/tefca-viewer` which does not exist. I wanted to confirm that when it's deploy, it will return to the actual home page.

yeah, this is an issue with `npm run dev`, but for it to work on dibbs.cloud we need the /tefca-viewer. I spent some time a few weeks back trying to see if there was a way to append or concatenate the /tefca-viewer depending on the mode you were in, but I could not get it to work.

It should still work in docker compose up.

**Comment by m-goggins** [comment]
Gotcha, @robertandremitchell, thanks for clarifying!

**Review by m-goggins — APPROVED** [review]

**Pull request merged**
