### PR TITLE
Tooltips1

### PR DESCRIPTION
**Pull request by aviars**
# PULL REQUEST

## Summary
What changes are being proposed?

Tooltips
## Related Issue
Fixes #
Adding tooltips
## Additional Information
Anything else the review team should know?
Tooltip on "Misc" still needs to be done. n ot clear how to add tootip to table summary.

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

[//]: # (PR title: Remember to name your PR descriptively!)

### CODE REVIEW

**Comment by aviars** [comment]
@nickbristow I just created a new branch and PR instead of trying to muck with the issues we encountered with merge conflicts/rebase.

**Comment by sarahtress** [comment]
> @sarahtress Screenshot 2024-04-30 at 10 08 31 AM Screenshot 2024-04-30 at 10 08 22 AM

@aviars thanks for sending the screenshots over! is this the default styling through USWDS? it just looks pretty different from what I see [here](https://designsystem.digital.gov/components/tooltip/) - it should match the styling in this link, unless they've changed it

**Comment by aviars** [comment]
@sarahtress   I see the tooltip a different color/looks different as well. I am applying `class="usa-tooltip"` on the spans like in the USWDS example.  So not sure where the CSS is for that.  May need to add/change that CSS.

**Comment by sarahtress** [comment]
> @sarahtress I see the tooltip a different color/looks different as well. I am applying `class="usa-tooltip"` on the spans like in the USWDS example. So not sure where the CSS is for that. May need to add/change that CSS.

@aviars I recommend pairing with @nickbristow to see if he's figured out the styling here on the other tooltip ticket!

**Comment by aviars** [comment]
all of the check have passed. Requesting review/merge.

**Comment by sarahtress** [comment]
just a reminder, this needs to pass design review before getting merged! thanks

**Comment by aviars** [comment]
Screenshot 2024-04-30 at 3 08 48 PM

Do we know why its rendering this way?

**Comment by aviars** [comment]
closing in favor of #1748

**Pull request closed without merging**
